### ISSUE TITLE
Mention ability to process log files in README.txt

### ISSUE THREAD

**Issue by ngirard** [stefanhepp/pplatex#1]
Hi Stefan,

the README.txt file, as it is, doesn't mention the fact that pplatex can also parse a log file produced by another tool or compilation process. I think it is a valuable feature, because it allows people to "plug" pplatex to their existing workflows, and as such, it deserves to be mentioned in the README -- pretty much the same way as in your "old" page, by the way (http://www.stefant.org/web/projects/software/pplatex.html).

Thanks in advance !

**Comment by stefanhepp** [comment]
Thanks for the hint! I (finally) updated the Readme to mention this feature.
