### ISSUE TITLE
Installation error on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by TryerGit** [stefanhepp/pplatex#20]
Hello,

I am trying to install / build from source. 

From https://github.com/stefanhepp/pplatex/releases I downloaded pplatex-pplatex-1.0-rc3.tar.gz

Then, I gave `tar -xf pplatex-pplatex-1.0-rc3.tar.gz` Then, I gave : `cd pplatex-pplatex-1.0-rc3/`

Then, I issued: `cmake -S src -B build`

This command informs me that `Build files have been written to: /mnt/c/Users/TryerGit/Downloads/pplatex-pplatex-1.0-rc3/build`

Then, I navigate to build folder via `cd build`. Issuing `make all` gives me the following error: 

```
:/mnt/c/Users/TryerGit/Downloads/pplatex-pplatex-1.0-rc3/build$ make all
Scanning dependencies of target pplatex
[ 16%] Building CXX object CMakeFiles/pplatex.dir/main.o
[ 33%] Building CXX object CMakeFiles/pplatex.dir/regex.o
[ 50%] Building CXX object CMakeFiles/pplatex.dir/outputinfo.o
[ 66%] Building CXX object CMakeFiles/pplatex.dir/outputfilter.o
[ 83%] Building CXX object CMakeFiles/pplatex.dir/latexoutputfilter.o
[100%] Linking CXX executable pplatex
/usr/bin/ld: CMakeFiles/pplatex.dir/regex.o: in function `Regex::Regex(char const*, bool)':
regex.cpp:(.text+0x6d): undefined reference to `pcreposix_regcomp'
/usr/bin/ld: regex.cpp:(.text+0xa0): undefined reference to `pcreposix_regerror'
/usr/bin/ld: CMakeFiles/pplatex.dir/regex.o: in function `Regex::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
regex.cpp:(.text+0x1f2): undefined reference to `pcreposix_regexec'
/usr/bin/ld: regex.cpp:(.text+0x23e): undefined reference to `pcreposix_regerror'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pplatex.dir/build.make:144: pplatex] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/pplatex.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

This was after I had done `sudo apt-get install libpcre3-dev`

I am trying to install `pplatex` so that the quick fix can correctly parse the error/warning log via VimTeX. Please see the issue I have raised regarding that [here](https://github.com/lervag/vimtex/issues/2543)

Any help regarding correct installation of pplatex is appreciated.

Thanks.

**Comment by TryerGit** [comment]
Never mind this thread.

I redid carefully the steps mentioned in the opening page and it seems to be up and running.

From https://github.com/stefanhepp/pplatex/releases I downloaded pplatex-pplatex-1.0-rc3.tar.gz to the /Downloads/ folder.

Then, I gave `tar -xf pplatex-pplatex-1.0-rc3.tar.gz` Then, I created a build folder: /Downloads/build/

From within this build folder, I issued "cmake ../pplatex-pplatex-1.0-rc3" followed by "make". This installs fine and I could find `pplatex` in the /Downloads/build/src folder. Then, I copied over this executable to ~/bin/ and issued `chmod u+x pplatex`

This was followed by updating the path variable in `.bashrc` to be something like:

`PATH=$PATH:~/bin`

Thanks!

**Comment by GTM52** [comment]
> Never mind this thread.
> 
> I redid carefully the steps mentioned in the opening page and it seems to be up and running.
> 
> From https://github.com/stefanhepp/pplatex/releases I downloaded pplatex-pplatex-1.0-rc3.tar.gz to the /Downloads/ folder.
> 
> Then, I gave `tar -xf pplatex-pplatex-1.0-rc3.tar.gz` Then, I created a build folder: /Downloads/build/
> 
> From within this build folder, I issued "cmake ../pplatex-pplatex-1.0-rc3" followed by "make". This installs fine and I could find `pplatex` in the /Downloads/build/src folder. Then, I copied over this executable to ~/bin/ and issued `chmod u+x pplatex`
> 
> This was followed by updating the path variable in `.bashrc` to be something like:
> 
> `PATH=$PATH:~/bin`
> 
> Thanks!

Sorry for bothering you, I followed your process and run the cmake. It seems fine, but I cannot find the `pplatex` file. I am also using WSL Ubuntu, could you provide the file for me?

Thank you!
