### ISSUE TITLE
Is there way to use another *tex

### ISSUE THREAD

**Issue by Kedrigern** [stefanhepp/pplatex#7]
Is there way to use another *TeX (XeLaTeX, LuaTeX, ...)?

**Comment by stefanhepp** [comment]
You can either use the pplatex -c option to set the latex program that is used, or you could use the -i option to just parse the log output that is produced by any program you called. On Linux, you can also check out the src/ppluatex script, rename it (if you want) and configure it to run any command you like (create a ~/.<nameofthescript>.conf file and put COMMAND=<your-latex-name> in it).

The only requirement is that the output of the tool is similar to what pdflatex or latex produces. At least luatex seems to be compatible in the relevant parts, to my knowledge. I have not tested it with (or used) XeLaTex before though.
